module.exports = {
  env: {
    browser: true,
    node: true,
  },
  rules: {
    'eol-last': 'warn',
    'no-alert': 'warn',
    'no-case-declarations': 'warn',
    'no-cond-assign': 'error',
    'no-console': ['warn', { allow: ['warn', 'error'] }],
    'no-debugger': 'warn',
    'no-extra-boolean-cast': 'warn',
    'no-global-assign': 'error',
    'no-invalid-this': 'warn',
    'no-lonely-if': 'warn',
    'no-mixed-spaces-and-tabs': 'warn',
    'no-return-assign': ['error', 'always'],
    'no-tabs': 'warn',
    'no-trailing-spaces': 'warn',
    'no-unneeded-ternary': 'warn',
    'no-unsafe-negation': 'error',
    'no-useless-return': 'warn',
    'no-var': 'warn',
    'prefer-const': 'warn',
    'prefer-template': 'warn',
    'require-await': 'warn',
    yoda: 'warn',

    'import/no-unresolved': 'error',

    'react/jsx-no-duplicate-props': 'warn',
    'react/jsx-sort-props': 'warn',
    'react/no-find-dom-node': 'warn',
    'react/no-redundant-should-component-update': 'error',
    'react/no-render-return-value': 'error',
    'react/no-string-refs': 'warn',
    'react/no-unknown-property': 'error',
    'react/no-unused-prop-types': 'warn',
    'react/no-will-update-set-state': 'error',
    'react/prefer-es6-class': ['warn', 'always'],
    'react/prefer-stateless-function': ['warn', { ignorePureComponents: true }],
    'react/prop-types': 'error',
    'react/react-in-jsx-scope': 'error',
    'react/require-default-props': 'warn',
    'react/require-render-return': 'error',
    'react/self-closing-comp': 'warn',
    'react/sort-prop-types': 'warn',
    'react/void-dom-elements-no-children': 'error',
    'sort-keys': 'warn',

    strict: 0,
  },
  plugins: ['import', 'react'],
  extends: ['react-app', 'plugin:import/errors', 'plugin:import/warnings'],
  settings: {
    'import/resolver': {
      webpack: {
        config: 'config/webpack/client.js',
      },
    },
  },
}
